OnEp = input("Δώσε Ονοματεπώνυμο: ")
odos = input("Δώσε τη Διεύθυνση σου: ")
poli = input("Δώσε την πόλη σου: ")
nomos = input("Δώσε τον νομό σου: ")
tk = input("Δώσε τον ΤΚ σου: ")
til = input("Δώσε το τηλέφωνό σου: ")
tmima = input("Δώσε το τμήμα στο οποίο σπουδάζεις: ")
print(OnEp)
print(odos, poli, nomos, tk, sep=', ')
print(til)
print(tmima)
